package quadrants.tools;

import haxe.Int64;
import haxe.io.FPHelper;
import haxe.io.Output;
import sys.io.File;

private typedef RegisteredPlyChannel = {
  var name:String;
  var data:PlyScalarData;
}

/**
  Deterministic PLY 1.0 writer for vertex properties and fixed-arity faces.

  Properties are registered in call order. `writeAscii` emits PLY ASCII and
  `writeBinaryLittleEndian` emits `binary_little_endian`; both validate the
  complete object before opening the destination file.
*/
class PlyWriter {
  public static inline var DEFAULT_COMMENT = "generated by Quadrants PlyWriter";

  public final vertexCount:Int;
  public final faceCount:Int;
  public final faceKind:PlyFaceKind;
  public final comment:String;

  final vertexChannels:Array<RegisteredPlyChannel> = [];
  final faceChannels:Array<RegisteredPlyChannel> = [];
  var faceIndices:Null<Array<Int>> = null;

  public function new(
    vertexCount:Int,
    faceCount:Int = 0,
    faceKind:PlyFaceKind = PlyFaceKind.Triangles,
    comment:String = DEFAULT_COMMENT) {
    if (vertexCount <= 0) {
      throw "PlyWriter vertexCount must be positive";
    }
    if (faceCount < 0) {
      throw "PlyWriter faceCount must be non-negative";
    }
    validateComment(comment);

    this.vertexCount = vertexCount;
    this.faceCount = faceCount;
    this.faceKind = faceKind;
    this.comment = comment;
  }

  public static function triangles(vertexCount:Int, faceCount:Int = 0, comment:String = DEFAULT_COMMENT):PlyWriter {
    return new PlyWriter(vertexCount, faceCount, PlyFaceKind.Triangles, comment);
  }

  public static function quads(vertexCount:Int, faceCount:Int = 0, comment:String = DEFAULT_COMMENT):PlyWriter {
    return new PlyWriter(vertexCount, faceCount, PlyFaceKind.Quads, comment);
  }

  /** Registers one scalar property for every vertex. */
  public function addVertexChannel(name:String, data:PlyScalarData):PlyWriter {
    registerChannels(vertexChannels, [{name: name, data: data}], vertexCount, "vertex");
    return this;
  }

  /** Registers one scalar property for every face. */
  public function addFaceChannel(name:String, data:PlyScalarData):PlyWriter {
    if (faceCount == 0) {
      throw "PlyWriter cannot register face properties when faceCount is zero";
    }
    registerChannels(faceChannels, [{name: name, data: data}], faceCount, "face");
    return this;
  }

  public function addVertexPosition(x:Array<Float>, y:Array<Float>, z:Array<Float>):PlyWriter {
    registerChannels(vertexChannels, [
      {name: "x", data: PlyScalarData.Float32(x)},
      {name: "y", data: PlyScalarData.Float32(y)},
      {name: "z", data: PlyScalarData.Float32(z)},
    ], vertexCount, "vertex");
    return this;
  }

  public function addVertexNormal(nx:Array<Float>, ny:Array<Float>, nz:Array<Float>):PlyWriter {
    registerChannels(vertexChannels, [
      {name: "nx", data: PlyScalarData.Float32(nx)},
      {name: "ny", data: PlyScalarData.Float32(ny)},
      {name: "nz", data: PlyScalarData.Float32(nz)},
    ], vertexCount, "vertex");
    return this;
  }

  public function addVertexVelocity(vx:Array<Float>, vy:Array<Float>, vz:Array<Float>):PlyWriter {
    registerChannels(vertexChannels, [
      {name: "vx", data: PlyScalarData.Float32(vx)},
      {name: "vy", data: PlyScalarData.Float32(vy)},
      {name: "vz", data: PlyScalarData.Float32(vz)},
    ], vertexCount, "vertex");
    return this;
  }

  public function addVertexColor(red:Array<Float>, green:Array<Float>, blue:Array<Float>):PlyWriter {
    registerChannels(vertexChannels, [
      {name: "red", data: PlyScalarData.Float32(red)},
      {name: "green", data: PlyScalarData.Float32(green)},
      {name: "blue", data: PlyScalarData.Float32(blue)},
    ], vertexCount, "vertex");
    return this;
  }

  public function addVertexAlpha(alpha:Array<Float>):PlyWriter {
    return addVertexChannel("alpha", PlyScalarData.Float32(alpha));
  }

  public function addVertexRgba(red:Array<Float>, green:Array<Float>, blue:Array<Float>, alpha:Array<Float>):PlyWriter {
    registerChannels(vertexChannels, [
      {name: "red", data: PlyScalarData.Float32(red)},
      {name: "green", data: PlyScalarData.Float32(green)},
      {name: "blue", data: PlyScalarData.Float32(blue)},
      {name: "alpha", data: PlyScalarData.Float32(alpha)},
    ], vertexCount, "vertex");
    return this;
  }

  public function addVertexId():PlyWriter {
    var ids = new Array<Int>();
    for (index in 0...vertexCount) {
      ids.push(index);
    }
    return addVertexChannel("id", PlyScalarData.Int32(ids));
  }

  public function addVertexPiece(piece:Array<Int>):PlyWriter {
    return addVertexChannel("piece", PlyScalarData.Int32(piece));
  }

  /**
    Replaces the fixed-arity face index buffer. The input is flattened in face
    order, with three indices per triangle or four indices per quad.
  */
  public function setFaces(indices:Array<Int>):PlyWriter {
    var expectedCount = checkedFaceIndexCount();
    if (indices == null || indices.length != expectedCount) {
      throw 'PlyWriter face index count must be ${expectedCount} for ${faceCount} ${faceKindName()} faces';
    }
    validateFaceIndices(indices);
    faceIndices = indices;
    return this;
  }

  public function setTriangleFaces(indices:Array<Int>):PlyWriter {
    if (faceKind != PlyFaceKind.Triangles) {
      throw "PlyWriter setTriangleFaces requires a triangle writer";
    }
    return setFaces(indices);
  }

  public function setQuadFaces(indices:Array<Int>):PlyWriter {
    if (faceKind != PlyFaceKind.Quads) {
      throw "PlyWriter setQuadFaces requires a quad writer";
    }
    return setFaces(indices);
  }

  /** Python-equivalent spelling for `setFaces`. */
  public inline function addFaces(indices:Array<Int>):PlyWriter {
    return setFaces(indices);
  }

  public function addFaceId():PlyWriter {
    var ids = new Array<Int>();
    for (index in 0...faceCount) {
      ids.push(index);
    }
    return addFaceChannel("id", PlyScalarData.Int32(ids));
  }

  public function addFacePiece(piece:Array<Int>):PlyWriter {
    return addFaceChannel("piece", PlyScalarData.Int32(piece));
  }

  /** Validates all mutable buffers without producing output. */
  public function validate():Void {
    validateComment(comment);
    validateChannels(vertexChannels, vertexCount, "vertex");
    requirePositionChannels();

    if (faceCount == 0) {
      if (faceChannels.length != 0) {
        throw "PlyWriter cannot emit face properties without faces";
      }
      if (faceIndices != null && faceIndices.length != 0) {
        throw "PlyWriter has face indices despite faceCount being zero";
      }
      return;
    }

    validateChannels(faceChannels, faceCount, "face");
    if (faceIndices == null) {
      throw "PlyWriter faces were declared but no face indices were supplied";
    }
    if (faceIndices.length != checkedFaceIndexCount()) {
      throw "PlyWriter face index count no longer matches faceCount";
    }
    validateFaceIndices(faceIndices);
  }

  /** Writes a standards-compliant deterministic PLY ASCII file. */
  public function writeAscii(path:String):Void {
    validate();
    writeToPath(path, function(output:Output):Void {
      output.bigEndian = false;
      output.writeString(header("ascii"));
      writeAsciiBody(output);
    });
  }

  /** Writes a standards-compliant deterministic little-endian binary PLY file. */
  public function writeBinaryLittleEndian(path:String):Void {
    validate();
    writeToPath(path, function(output:Output):Void {
      output.bigEndian = false;
      output.writeString(header("binary_little_endian"));
      writeBinaryBody(output);
    });
  }

  public inline function exportAscii(path:String):Void {
    writeAscii(path);
  }

  /** Equivalent to the Python writer's default binary export, fixed to little endian. */
  public inline function export(path:String):Void {
    writeBinaryLittleEndian(path);
  }

  private function writeAsciiBody(output:Output):Void {
    for (vertex in 0...vertexCount) {
      for (channel in vertexChannels) {
        output.writeString(scalarAsAscii(channel.data, vertex));
        output.writeByte(32);
      }
      output.writeByte(10);
    }

    if (faceCount == 0) {
      return;
    }

    var arity = faceArity();
    var indices = faceIndices;
    for (face in 0...faceCount) {
      output.writeString(Std.string(arity));
      output.writeByte(32);
      var offset = face * arity;
      for (component in 0...arity) {
        output.writeString(Std.string(indices[offset + component]));
        output.writeByte(32);
      }
      for (channel in faceChannels) {
        output.writeString(scalarAsAscii(channel.data, face));
        output.writeByte(32);
      }
      output.writeByte(10);
    }
  }

  private function writeBinaryBody(output:Output):Void {
    for (vertex in 0...vertexCount) {
      for (channel in vertexChannels) {
        writeScalarBinary(output, channel.data, vertex);
      }
    }

    if (faceCount == 0) {
      return;
    }

    var arity = faceArity();
    var indices = faceIndices;
    for (face in 0...faceCount) {
      output.writeByte(arity);
      var offset = face * arity;
      for (component in 0...arity) {
        output.writeInt32(indices[offset + component]);
      }
      for (channel in faceChannels) {
        writeScalarBinary(output, channel.data, face);
      }
    }
  }

  private function header(format:String):String {
    var output = new StringBuf();
    output.add("ply\n");
    output.add("format ");
    output.add(format);
    output.add(" 1.0\n");
    output.add("comment ");
    output.add(comment);
    output.add("\n");
    output.add("element vertex ");
    output.add(Std.string(vertexCount));
    output.add("\n");
    for (channel in vertexChannels) {
      output.add("property ");
      output.add(scalarTypeName(channel.data));
      output.add(" ");
      output.add(channel.name);
      output.add("\n");
    }
    if (faceCount > 0) {
      output.add("element face ");
      output.add(Std.string(faceCount));
      output.add("\n");
      output.add("property list uchar int vertex_indices\n");
      for (channel in faceChannels) {
        output.add("property ");
        output.add(scalarTypeName(channel.data));
        output.add(" ");
        output.add(channel.name);
        output.add("\n");
      }
    }
    output.add("end_header\n");
    return output.toString();
  }

  private static function registerChannels(
    target:Array<RegisteredPlyChannel>,
    added:Array<RegisteredPlyChannel>,
    expectedCount:Int,
    elementName:String):Void {
    if (added == null || added.length == 0) {
      throw 'PlyWriter requires at least one ${elementName} property';
    }

    for (channel in added) {
      if (channel == null) {
        throw 'PlyWriter ${elementName} property cannot be null';
      }
      validatePropertyName(channel.name);
      validateScalarData(channel.data, expectedCount, '${elementName} property ${channel.name}');
      if (hasChannel(target, channel.name)) {
        throw 'PlyWriter duplicate ${elementName} property ${channel.name}';
      }
      for (other in added) {
        if (other != channel && other != null && other.name == channel.name) {
          throw 'PlyWriter duplicate ${elementName} property ${channel.name}';
        }
      }
    }

    for (channel in added) {
      target.push(channel);
    }
  }

  private static function validateChannels(channels:Array<RegisteredPlyChannel>, expectedCount:Int, elementName:String):Void {
    for (channel in channels) {
      if (channel == null) {
        throw 'PlyWriter ${elementName} property cannot be null';
      }
      validatePropertyName(channel.name);
      validateScalarData(channel.data, expectedCount, '${elementName} property ${channel.name}');
      for (other in channels) {
        if (other != channel && other != null && other.name == channel.name) {
          throw 'PlyWriter duplicate ${elementName} property ${channel.name}';
        }
      }
    }
  }

  private function requirePositionChannels():Void {
    if (!hasChannel(vertexChannels, "x") || !hasChannel(vertexChannels, "y") || !hasChannel(vertexChannels, "z")) {
      throw "PlyWriter requires x, y, and z vertex properties";
    }
  }

  private function validateFaceIndices(indices:Array<Int>):Void {
    for (index in indices) {
      if (index < 0 || index >= vertexCount) {
        throw 'PlyWriter face index ${index} is outside [0, ${vertexCount})';
      }
    }
  }

  private function checkedFaceIndexCount():Int {
    var arity = faceArity();
    if (faceCount > Std.int(0x7fffffff / arity)) {
      throw "PlyWriter face index count exceeds the Haxe array limit";
    }
    return faceCount * arity;
  }

  private function faceArity():Int {
    return switch (faceKind) {
      case PlyFaceKind.Triangles: 3;
      case PlyFaceKind.Quads: 4;
    };
  }

  private function faceKindName():String {
    return switch (faceKind) {
      case PlyFaceKind.Triangles: "triangle";
      case PlyFaceKind.Quads: "quad";
    };
  }

  private static function hasChannel(channels:Array<RegisteredPlyChannel>, name:String):Bool {
    for (channel in channels) {
      if (channel != null && channel.name == name) {
        return true;
      }
    }
    return false;
  }

  private static function scalarTypeName(data:PlyScalarData):String {
    return switch (data) {
      case PlyScalarData.Int8(_): "char";
      case PlyScalarData.UInt8(_): "uchar";
      case PlyScalarData.Int16(_): "short";
      case PlyScalarData.UInt16(_): "ushort";
      case PlyScalarData.Int32(_): "int";
      case PlyScalarData.UInt32(_): "uint";
      case PlyScalarData.Float32(_): "float";
      case PlyScalarData.Float64(_): "double";
    };
  }

  private static function scalarAsAscii(data:PlyScalarData, index:Int):String {
    return switch (data) {
      case PlyScalarData.Int8(values) | PlyScalarData.UInt8(values) | PlyScalarData.Int16(values) | PlyScalarData.UInt16(values) | PlyScalarData.Int32(values):
        Std.string(values[index]);
      case PlyScalarData.UInt32(values):
        Int64.toStr(values[index]);
      case PlyScalarData.Float32(values):
        formatFloat32(values[index]);
      case PlyScalarData.Float64(values):
        formatFloat64(values[index]);
    };
  }

  private static function writeScalarBinary(output:Output, data:PlyScalarData, index:Int):Void {
    switch (data) {
      case PlyScalarData.Int8(values):
        output.writeInt8(values[index]);
      case PlyScalarData.UInt8(values):
        output.writeByte(values[index]);
      case PlyScalarData.Int16(values):
        output.writeInt16(values[index]);
      case PlyScalarData.UInt16(values):
        output.writeUInt16(values[index]);
      case PlyScalarData.Int32(values):
        output.writeInt32(values[index]);
      case PlyScalarData.UInt32(values):
        output.writeInt32(values[index].low);
      case PlyScalarData.Float32(values):
        output.writeFloat(values[index]);
      case PlyScalarData.Float64(values):
        output.writeDouble(values[index]);
    }
  }

  private static function validateScalarData(data:PlyScalarData, expectedCount:Int, label:String):Void {
    if (data == null) {
      throw 'PlyWriter ${label} data is required';
    }
    switch (data) {
      case PlyScalarData.Int8(values):
        validateIntRange(values, expectedCount, -128, 127, label);
      case PlyScalarData.UInt8(values):
        validateIntRange(values, expectedCount, 0, 255, label);
      case PlyScalarData.Int16(values):
        validateIntRange(values, expectedCount, -32768, 32767, label);
      case PlyScalarData.UInt16(values):
        validateIntRange(values, expectedCount, 0, 65535, label);
      case PlyScalarData.Int32(values):
        validateIntRange(values, expectedCount, -2147483648, 2147483647, label);
      case PlyScalarData.UInt32(values):
        validateUInt32(values, expectedCount, label);
      case PlyScalarData.Float32(values):
        validateFloatRange(values, expectedCount, label, true);
      case PlyScalarData.Float64(values):
        validateFloatRange(values, expectedCount, label, false);
    }
  }

  private static function validateIntRange(values:Array<Int>, expectedCount:Int, minimum:Int, maximum:Int, label:String):Void {
    if (values == null || values.length != expectedCount) {
      throw 'PlyWriter ${label} length must be ${expectedCount}';
    }
    for (value in values) {
      if (value < minimum || value > maximum) {
        throw 'PlyWriter ${label} value ${value} is outside [${minimum}, ${maximum}]';
      }
    }
  }

  private static function validateUInt32(values:Array<Int64>, expectedCount:Int, label:String):Void {
    if (values == null || values.length != expectedCount) {
      throw 'PlyWriter ${label} length must be ${expectedCount}';
    }
    var zero = Int64.ofInt(0);
    var maximum = Int64.make(0, -1);
    for (value in values) {
      if (Int64.compare(value, zero) < 0 || Int64.compare(value, maximum) > 0) {
        throw 'PlyWriter ${label} value ${Int64.toStr(value)} is outside the PLY uint range';
      }
    }
  }

  private static function validateFloatRange(values:Array<Float>, expectedCount:Int, label:String, singlePrecision:Bool):Void {
    if (values == null || values.length != expectedCount) {
      throw 'PlyWriter ${label} length must be ${expectedCount}';
    }
    for (value in values) {
      if (!Math.isFinite(value)) {
        throw 'PlyWriter ${label} must not contain NaN or infinity';
      }
      if (singlePrecision && !Math.isFinite(FPHelper.i32ToFloat(FPHelper.floatToI32(value)))) {
        throw 'PlyWriter ${label} contains a value that overflows PLY float';
      }
    }
  }

  private static function formatFloat32(value:Float):String {
    return Std.string(FPHelper.i32ToFloat(FPHelper.floatToI32(value)));
  }

  private static function formatFloat64(value:Float):String {
    return Std.string(value);
  }

  private static function validatePropertyName(name:String):Void {
    if (name == null || name.length == 0 || !isIdentifier(name)) {
      throw "PlyWriter property names must be ASCII identifiers";
    }
  }

  private static function isIdentifier(value:String):Bool {
    for (index in 0...value.length) {
      var code = StringTools.fastCodeAt(value, index);
      var letter = (code >= 65 && code <= 90) || (code >= 97 && code <= 122);
      var digit = code >= 48 && code <= 57;
      if (index == 0 ? !(letter || code == 95) : !(letter || digit || code == 95)) {
        return false;
      }
    }
    return true;
  }

  private static function validateComment(value:String):Void {
    if (value == null || value.indexOf("\n") >= 0 || value.indexOf("\r") >= 0 || value.indexOf("\x00") >= 0) {
      throw "PlyWriter comment must be a single non-NUL line";
    }
  }

  private static function writeToPath(path:String, write:Output->Void):Void {
    if (path == null || path.length == 0) {
      throw "PlyWriter output path is required";
    }
    var output = File.write(path, true);
    try {
      write(output);
      output.close();
    } catch (error:Dynamic) {
      try {
        output.close();
      } catch (_:Dynamic) {}
      throw error;
    }
  }
}
