import haxe.io.Path;
import sys.FileSystem;
import sys.io.File;
using StringTools;

class BuildConditionKernelFatbin {
  static final SM_VERSIONS:Array<Int> = [90, 100, 110, 120];

  static function main():Void {
    var repo = findRepoRoot();
    var nvcc = findNvcc();
    var src = Path.join([repo, "quadrants", "runtime", "cuda", "graph_do_while_cond.cu"]);
    var outHeader = Path.join([repo, "quadrants", "runtime", "cuda", "graph_do_while_cond_fatbin.h"]);
    var tmp = makeTempDir();

    try {
      var obj = Path.join([tmp, "condition_kernel.o"]);
      var fatbin = Path.join([tmp, "condition_kernel.fatbin"]);
      var smTargets = smTargetArgs();

      Sys.println("Compiling ...");
      run(nvcc, ["-dc", "-rdc=true"].concat(smTargets).concat([src, "-o", obj]));

      Sys.println("Device-linking with libcudadevrt ...");
      run(nvcc, ["-dlink"].concat(smTargets).concat([obj, "-lcudadevrt", "-fatbin", "-o", fatbin]));

      Sys.println("Generating C header ...");
      generateHeader(fatbin, outHeader);
      cleanup(tmp);
      Sys.println("Done.");
    } catch (e:Dynamic) {
      cleanup(tmp);
      throw e;
    }
  }

  static function smTargetArgs():Array<String> {
    var result = [];
    for (sm in SM_VERSIONS) {
      result.push('-gencode=arch=compute_$sm,code=sm_$sm');
    }
    return result;
  }

  static function run(cmd:String, args:Array<String>):Void {
    Sys.println("  " + quoteCommand(cmd, args));
    var code = Sys.command(cmd, args);
    if (code != 0) {
      throw 'Command failed with exit code $code: ${quoteCommand(cmd, args)}';
    }
  }

  static function generateHeader(fatbinPath:String, outPath:String):Void {
    var bytes = File.getBytes(fatbinPath);
    var buf = new StringBuf();
    buf.add("// Auto-generated by scripts/BuildConditionKernelFatbin.hx\n");
    buf.add("// Do not edit manually. Regenerate with:\n");
    buf.add("//   haxe scripts/build_condition_kernel_fatbin.hxml && hl build_condition_kernel_fatbin.hl\n");
    buf.add("//\n");
    buf.add("// Source: quadrants/runtime/cuda/graph_do_while_cond.cu\n");
    buf.add("// SM targets: " + [for (sm in SM_VERSIONS) 'sm_$sm'].join(", ") + "\n");
    buf.add('// Size: ${bytes.length} bytes\n');
    buf.add("\n");
    buf.add("#pragma once\n\n");
    buf.add("#include <cstddef>\n\n");
    buf.add("static const unsigned char kConditionKernelFatbin[] = {\n");
    for (i in 0...bytes.length) {
      if (i % 12 == 0) {
        buf.add("    ");
      }
      buf.add("0x" + StringTools.hex(bytes.get(i), 2).toLowerCase() + ",");
      if (i % 12 == 11 || i == bytes.length - 1) {
        buf.add("\n");
      } else {
        buf.add(" ");
      }
    }
    buf.add("};\n\n");
    buf.add('static const std::size_t kConditionKernelFatbinSize = ${bytes.length};\n');
    buf.add("\n");
    File.saveContent(outPath, buf.toString());
    Sys.println('Wrote $outPath (${bytes.length} bytes)');
  }

  static function findRepoRoot():String {
    var current = FileSystem.fullPath(Sys.getCwd());
    while (true) {
      var marker = Path.join([current, "quadrants", "runtime", "cuda", "graph_do_while_cond.cu"]);
      if (FileSystem.exists(marker)) {
        return current;
      }
      var parent = Path.directory(current);
      if (parent == current || parent == "") {
        throw "Run this script from the Quadrants source tree";
      }
      current = parent;
    }
    throw "unreachable";
  }

  static function findNvcc():String {
    var explicit = Sys.getEnv("NVCC");
    if (isExecutable(explicit)) {
      return explicit;
    }

    for (envName in ["CUDA_HOME", "CUDA_PATH"]) {
      var root = Sys.getEnv(envName);
      if (root != null && root.length > 0) {
        var candidate = Path.join([root, "bin", nvccName()]);
        if (isExecutable(candidate)) {
          return candidate;
        }
      }
    }

    var path = Sys.getEnv("PATH");
    if (path != null) {
      for (dir in path.split(pathSeparator())) {
        if (dir.length == 0) {
          continue;
        }
        var candidate = Path.join([dir, nvccName()]);
        if (isExecutable(candidate)) {
          return candidate;
        }
      }
    }

    var defaultPath = "/usr/local/cuda/bin/nvcc";
    if (isExecutable(defaultPath)) {
      return defaultPath;
    }

    throw "nvcc not found. Install the CUDA toolkit and add it to PATH, set NVCC, or set CUDA_HOME.";
  }

  static function nvccName():String {
    return Sys.systemName() == "Windows" ? "nvcc.exe" : "nvcc";
  }

  static function pathSeparator():String {
    return Sys.systemName() == "Windows" ? ";" : ":";
  }

  static function isExecutable(path:Null<String>):Bool {
    return path != null && path.length > 0 && FileSystem.exists(path) && !FileSystem.isDirectory(path);
  }

  static function makeTempDir():String {
    var base = firstNonEmpty([Sys.getEnv("TMPDIR"), Sys.getEnv("TEMP"), Sys.getEnv("TMP")]);
    if (base == null) {
      base = Sys.systemName() == "Windows" ? Sys.getCwd() : "/tmp";
    }

    while (true) {
      var candidate = Path.join([base, 'qd-fatbin-${Std.int(Sys.time() * 1000)}-${Std.random(1000000)}']);
      if (!FileSystem.exists(candidate)) {
        FileSystem.createDirectory(candidate);
        return candidate;
      }
    }
    throw "unreachable";
  }

  static function firstNonEmpty(values:Array<Null<String>>):Null<String> {
    for (value in values) {
      if (value != null && value.length > 0) {
        return value;
      }
    }
    return null;
  }

  static function cleanup(path:String):Void {
    if (!FileSystem.exists(path)) {
      return;
    }
    for (entry in FileSystem.readDirectory(path)) {
      var child = Path.join([path, entry]);
      if (FileSystem.isDirectory(child)) {
        cleanup(child);
      } else {
        FileSystem.deleteFile(child);
      }
    }
    FileSystem.deleteDirectory(path);
  }

  static function quoteCommand(cmd:String, args:Array<String>):String {
    return [cmd].concat(args).map(quoteArg).join(" ");
  }

  static function quoteArg(arg:String):String {
    if (arg.indexOf(" ") < 0 && arg.indexOf("\t") < 0 && arg.indexOf("\"") < 0) {
      return arg;
    }
    return "\"" + arg.split("\"").join("\\\"") + "\"";
  }
}
