name: clang-tidy (static analysis)

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: clang-tidy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Prerequisites
        run: bash .github/workflows/scripts_new/clang_tidy/1_prerequisites.sh
      - name: Configure
        run: bash .github/workflows/scripts_new/clang_tidy/2_build.sh
      - name: Clang-tidy
        run: bash .github/workflows/scripts_new/clang_tidy/3_test.sh
